<a href="https://colab.research.google.com/github/bbusraoz/Assignments/blob/main/Assignment_1_Student.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [ ]:
import numpy as np

#### 2. Create an array from my_list=[5,10,15,20,25]

In [ ]:
my_list = [5,10,15,20,25]
np.array(my_list)

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array 5x5 zeros 

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array 4x4 ones assign data type int

In [ ]:
np.ones((4,4), dtype="int")

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### 5. Make all the values of the array above 7

In [ ]:
np.ones((4,4), dtype="int")*7

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 6. Create same array above with full method

In [ ]:
np.full((4,4),7,dtype="int")

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 

In [ ]:
np.arange(2,17,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with values between 0 to 25

In [ ]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with values between 0 to 25 using linspace

In [ ]:
np.linspace(0,25,25,dtype = "int", endpoint = False).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 10. Create 5 random number with numpy

In [ ]:
np.random.rand(5)

array([0.9278869 , 0.85474323, 0.79021562, 0.68137763, 0.06681865])

#### 11. Create random normal distributed 5x5 array

In [ ]:
np.random.randn(5,5)

array([[ 1.171343  ,  0.81052159,  1.31991048,  1.38579845, -0.43268239],
       [ 0.47165284,  0.05216267,  0.5287543 ,  1.30820424, -1.51592213],
       [-0.06225604, -0.56647698, -1.15742096,  0.33982973,  0.66610899],
       [ 0.75224688, -0.34442812, -0.60227055, -0.79030417, -1.04242892],
       [-0.24421129, -0.08403539, -0.94063908,  0.88537431, -0.07353419]])

#### 12. Create 3x4 shaped array with random int numbers between 20 and 50 with numpy

In [ ]:
np.random.randint(20,50, size = (3,4))

array([[25, 29, 34, 47],
       [23, 23, 39, 39],
       [38, 40, 42, 36]])

#### 13. Reshape the array below with shape 6x8

In [ ]:
ranarr = np.random.randint(0,60,48)

In [ ]:
ranarr

array([46, 39, 45, 38, 44, 20, 24, 31, 45,  9, 34, 19,  5, 27, 22, 49, 13,
       21, 25, 18, 40, 19, 15,  2, 29, 54, 40, 25, 42, 15, 51, 11, 33, 35,
       42, 18,  3, 30, 29,  5, 33, 46,  1, 13,  2,  8, 35, 33])

In [ ]:
ranarr.reshape(6,8)

array([[46, 39, 45, 38, 44, 20, 24, 31],
       [45,  9, 34, 19,  5, 27, 22, 49],
       [13, 21, 25, 18, 40, 19, 15,  2],
       [29, 54, 40, 25, 42, 15, 51, 11],
       [33, 35, 42, 18,  3, 30, 29,  5],
       [33, 46,  1, 13,  2,  8, 35, 33]])

In [ ]:
#reshape with -1
ranarr.reshape(-1,8)

array([[46, 39, 45, 38, 44, 20, 24, 31],
       [45,  9, 34, 19,  5, 27, 22, 49],
       [13, 21, 25, 18, 40, 19, 15,  2],
       [29, 54, 40, 25, 42, 15, 51, 11],
       [33, 35, 42, 18,  3, 30, 29,  5],
       [33, 46,  1, 13,  2,  8, 35, 33]])

## Numpy Indexing and Selection


In [ ]:
#Create array below
mat= np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Write code that reproduces the output shown below.<br>

In [ ]:
mat[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array.

In [ ]:
mat[:,0]

array([ 1,  5,  9, 13])

#### 16. Get the values in 2nd row for every 2 step.

In [ ]:
mat[1,::2]

array([5, 7])

#### 17.Assign 77 to every cell in 3rd column.

In [ ]:
mat[:,2] = 77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [ ]:

mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 2nd row 1st column, 4th row 2nd column.

In [ ]:
mat[[1,3],[0,1]]

array([ 5, 14])

#### 19. Take between 2nd and last row with step 2 and between 1 and last column with step 2.

In [ ]:
mat[1::2,0::2]

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [ ]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [ ]:
mat[mat<10]

array([1, 2, 4, 5, 6, 8, 9])

In [ ]:
mat[mat>12]

array([77, 77, 77, 13, 14, 77, 16])

In [ ]:
mat[mat<10] + mat[mat>12]

array([78, 79, 81, 18, 20, 85, 25])

#### 21. Get the standard deviation of the result above

In [ ]:
(mat[mat<10] + mat[mat>12]).std()

29.700546274093877

#### 22. Get the sum of second column from array above

In [ ]:
#print array here
mat[:,2] = [3,7,11,15]
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
mat[:,1].sum(axis = 0)


32

#### 23. Get the median,mean and std of 3rd row from array above

In [ ]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
mat[2]

array([ 9, 10, 11, 12])

In [ ]:
#median
np.median(mat[2])

10.5

In [ ]:
#mean
np.mean(mat[2])

10.5

In [ ]:
#std
np.std(mat[2])

1.118033988749895

# Pandas Section

In [ ]:
import pandas as pd

**Read Salaries.csv take a look at first 5 rows, df info and df statistical measurements**

In [ ]:
sal=pd.read_csv('Salaries.csv')


In [ ]:
sal.head()

3  ...  Unnamed: 10
78779 Julio E Bandoni                Police Officer 3  ...          NaN
78780 Patrick  Burton         Court Staff Attorney II  ...          NaN
78781 Eric  Louie                         Firefighter  ...          NaN
78782 James M Blue     Senior Water Service Inspector  ...          NaN
78783 Jerry L King                   Police Officer 3  ...          NaN

[5 rows x 11 columns]

In [ ]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [ ]:
sal.describe()

123471.11        4790.94  ...  Unnamed: 8  Unnamed: 10
count   69267.000000   69872.000000  ...         0.0          0.0
mean    62284.230358    4349.920499  ...         NaN          NaN
std     40187.718192    9880.881024  ...         NaN          NaN
min         0.000000      -0.010000  ...         NaN          NaN
25%     28047.880000       0.000000  ...         NaN          NaN
50%     63690.310000       0.000000  ...         NaN          NaN
75%     89289.600000    3841.910000  ...         NaN          NaN
max    318835.490000  173547.730000  ...         NaN          NaN

[8 rows x 9 columns]

**How many different year value are there**

In [ ]:
sal

3  ...  Unnamed: 10
78779  Julio E Bandoni                Police Officer 3  ...          NaN
78780  Patrick  Burton         Court Staff Attorney II  ...          NaN
78781  Eric  Louie                         Firefighter  ...          NaN
78782  James M Blue     Senior Water Service Inspector  ...          NaN
78783  Jerry L King                   Police Officer 3  ...          NaN
...                                                ...  ...          ...
148650 Roy I Tillery                         Custodian  ...          NaN
148651 Not provided                       Not provided  ...          NaN
148652 Not provided                       Not provided  ...          NaN
148653 Not provided                       Not provided  ...          NaN
148654 Joe Lopez            Counselor, Log Cabin Ranch  ...          NaN

[69876 rows x 11 columns]

In [ ]:
sal.2013.value_counts()

SyntaxError: ignored

**Print out max and avg Totalpay**

In [ ]:
#max
sal.TotalPay.max()

AttributeError: ignored

In [ ]:
#avg
sal.TotalPay.mean()

74768.321971703

**How many records are there which have TotalPay bigger than avg TotalPay**

In [ ]:
len(sal[sal.TotalPay>sal.TotalPay.mean()])

69489

**How much does ALBERT PARDINI make (including benefits)?**

In [ ]:
sal[sal["EmployeeName"] == "ALBERT PARDINI"]["TotalPayBenefits"]

2    335279.91
Name: TotalPayBenefits, dtype: float64

**Who is lowest paid person**

In [ ]:
sal[sal.TotalPayBenefits ==sal.TotalPayBenefits.min()]["EmployeeName"]

148653    Joe Lopez
Name: EmployeeName, dtype: object

**What are the unique Jobs in dataset?**

In [ ]:
sal["JobTitle"].unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

**List 3 least common Jobs**

In [ ]:
sal.JobTitle.value_counts().tail(3)

COURT COMPUTER FACILITIES COORDINATOR             1
AUTOMOTIVE BODY AND FENDER WORKER SUPERVISOR I    1
VICTIM & WITNESS TECHNICIAN                       1
Name: JobTitle, dtype: int64

**How many people earned more than avg in 2012**

In [ ]:
sal[(sal.TotalPayBenefits>sal.TotalPayBnefits.mean()) & (sal.Year == 2012)]["EmployeeName"].count()

20366

**How many people have the word Manager in their job title?**

In [ ]:
#use apply function here
def manager_func(x):
  if "manager" in x.lower():
    return True
  else:
    return False

4110

In [ ]:
len(sal[sal.JobTitle.apply(lambda x:manager_func(x))])   #len(salary[salary.JobTitle.apply(lambda x: True if 'manager' in x.lower() else False)])

**Take Id,EmployeeName,JobTitle,TotalPay and TotalPayBenefits columns with iloc and assign it as sal_new dataframe**

In [ ]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [ ]:
sal_new= 
sal_new

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle   TotalPay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43   
1                      CAPTAIN III (POLICE DEPARTMENT)  538909.28   
2                      CAPTAIN III (POLICE DEPARTMENT)  335279.91   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided       0.00   
148651                                    Not provided       0.00   
148652                                    Not provided       0.00   
148653                      Counselor, Log Cabin Ranch    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 5 columns]

**Take columns betweeen EmployeeName and TotalPayBenefits with loc and assign it o sal_new df**
 

In [ ]:
sal_new=
sal_new

EmployeeName                                        JobTitle  \
0          NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1            GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2          ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3       CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4         PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
...                   ...                                             ...   
148649      Roy I Tillery                                       Custodian   
148650       Not provided                                    Not provided   
148651       Not provided                                    Not provided   
148652       Not provided                                    Not provided   
148653          Joe Lopez                      Counselor, Log Cabin Ranch   

         TotalPay  TotalPayBenefits  
0       567595.43         567595.43  
1       538909.28         538909.28  
2       335279.91         335279.91  
3       332343.61         332343.61  
4       326373.19         326373.19  
...           ...               ...  
148649       0.00              0.00  
148650       0.00              0.00  
148651       0.00              0.00  
148652       0.00              0.00  
148653    -618.13           -618.13  

[148654 rows x 4 columns]

**Print out the names of the employees who earn more than min, but less than avg**

10806            KWE LEE
10807     MIGUEL CARO JR
10808      JOANNE MORRIS
10809      LAYLA WELBORN
10810            LE BANH
               ...      
148648       Leon Walker
148649     Roy I Tillery
148650      Not provided
148651      Not provided
148652      Not provided
Name: EmployeeName, Length: 75649, dtype: object